### ISSUE TITLE
Translation helpers in operation and contract

### ISSUE THREAD

**Issue by johnlane** [apotonick/trailblazer#77]
Use of Rails' Translation helpers in operations and contracts requires two things:

* including the helper: `include ActionView::Helpers::TranslationHelper`
* setting the translation path: `@virtual_path`

I hae been trying to come up with a consistent way to achieve this but I have only achieved partial success. Here is what I have discovered/achieved:

The helper can be centrally included in an initializer but the `@virtual_path` is an instance variable that needs to be set when an object is instantiated. The best that I've been able to come up with is this initializer:

    module Trailblazer::Translations
      include ActionView::Helpers::TranslationHelper
      def initialize(*args)
        @virtual_path=self.class.to_s.downcase.gsub('::','.')
        super
      end
    end

    class Trailblazer::Operation
      prepend Trailblazer::Translations
    end

    class Reform::Contract
      prepend Trailblazer::Translations
    end

This works as expected for the operation. The example `t('.thing')` results in a translation path of `concept.operation.thing`.

However, it doesn't work as expected for the contract becase it is instantiated as an anonymous class. A similar example of `t('.thing)'` results in

        en-GB.#&lt;class:0xb3ba1cc0&gt;.thing

Could this idea be taken into trb in such a way that it works for operations, contracts, plus any other areas where it may be relevant but I haven't myself yet encountered...?

**Comment by apotonick** [comment]
Interesting! Cool idea! 

I didn't even think of using `TranslationHelper` in ops and forms, maybe because of the `ActionView` prefix. We should implement our own and see how much we can use from the original I18n gem. This will also allow to use that feature in other frameworks like Lotus or Roda, without having to pull in actionview (geez).

Why the refinements, though? This could be included explicitly in an initializer. I actually don't use refinements because it is a horrible concept (monkey-patching) taken to the language level, making it even worse. Anyway :stuck_out_tongue_winking_eye: 

We could make I18n in all TRB gems with a compositional approach where the translation logic is encapsulated in a `Translate` object or something. This way, we could share this code between all layers without including?

**Comment by johnlane** [comment]
I only monkey-patched bcause I needed to set up an instance variable in a yet-to-be-instantiated object. I wouldn't normally do that (I agree with your setiment) but I could not think of another way. I assumed you'd propose something better due to your knowledge of the TRB plumbing...

It would be good to have a TRB i18n implementation that, perhaps, did things a little better. Things I had thought of (but dismissed as not being possible) include

* recursing translation searches up the hierarchy
* being able to store i18n yml files under `app/concepts`.

@fernandes suggested a work-around for the anonymous class might be achievable by usinga separate reform contract class instead of inlining it. However, I think the inline approach is cleaner and it would be a shame to have to break that just to make translations work.

**Comment by johnlane** [comment]
I am just recording a note here. The below monkey-patch (bad, I know!!) works for an anonymous contract (it gives it a predictable path of `reform.form.thing`) : 
```ruby
    def initialize(*args)
      c = self.class
      while c.to_s.match /#<Class:0x[\da-f]+>/ do; c = c.superclass; end
      @virtual_path=c.to_s.downcase.gsub('::','.')
      super
    end

**Comment by apotonick** [comment]
Two things are not appreciated in ActiveModel's I18N style:

1. It introspects class names. We will use `model_name` for that, which has to be set explicitly via the `Model` module.
2. It blindly traverses up the inheritance chain, testing whether or not the next classes `respond_to?` this and that method. Again, I would rather have an explicit class option here. Also, most people do not seem to use this mechanism anyway, so we might probably do the similar thing we did in Cells, with "one path" per class?

I know that you're just outlining things, but to give you an idea about my opinions, I had to tell you what techniques to avoid. The above issues have given me head- and heartache many many times in Cells, Roar and Reform, so we should _not_ copy them.

Thanks for your work, man!!!

**Comment by fernandes** [comment]
@johnlane my suggestion is to have a class that is not a anonymous class heheh

here we just do translations this way, for example for a Thing concept

we have a `app/concepts/thing/views/new.haml` view, and inside we use translations path like this:

```ruby
i18n.t 'concepts.thing.new.string'
```

as we are not using the rails _lazy lookup_ theres no problem using the inline contract, maybe this can helps you

**Comment by apotonick** [comment]
We're all talking about the same, haha. 

What we want is a **generic translation path** "behavior" for **cells/views**, **form** validation errors and fields, **operation** messages (for example, when an operation computes a flash or log message), and even **representers** for APIs (when you had a translated API).

It should be something like @fernandes suggests, e.g. `concepts.thing.create`. I strongly discourage a inheritance mechanism, though, as I have a feeling people don't use this and it overcomplicates our code. Thoughts?

**Comment by johnlane** [comment]
I have a working RUDIMENTARY module that does translations without requiring ActionView. It does rely on the I18n gem however, but that isn't Rails so I hope that's ok. I'm going to throw a quick test app togeher to share whatI have done. I haven't finished but wanted to let you guys know I've had a degree of success.

A couple of points to note:

1. I had coded up an introspective path discovery before reading the above comment. It works but I take your point, so perhaps we can discuss that when I've uploaded my test app.

2. I think whether you use relative or absolute i18n paths is a personal choice and that both should work. We should supply sensible defaults but allow customisation. Again we can dicuss when I've uploaded.

Hope to have something to show you later today :)

**Comment by fernandes** [comment]
1. great to have own trailblazer translation paths :)

2. As you said, its a personal choice, and we decided to use absolute view related paths, once people who are translating is more used to a view perspective to a implementation perspective (just telling in hope this can helps other people), and I'm :+1: to provide defaults and allow customization.

**Comment by johnlane** [comment]
Take a look at https://github.com/johnlane/trailblazer-translation. Read the README (not README.rdoc) for furthr information.

**Comment by fernandes** [comment]
saw the code working for translation on concept view and locale file, really good

**Comment by johnlane** [comment]
Just a little update - I've been using my module successfully with operations, contracts and cells. I made a little tweak so it reports the full requested path when it fails to translate.

Also, II've been thinking about the translation path and auto-generating it from the class name. What I have right now, being based on the namespaced class name, is a bit naff for Cells because you get `someconcept.cell.thing` whereas what would be ideal is just `someconcept.thing`. I don't know if it's getting too clever but, perhaps, retrying paths after removing intermediate levels whose names match certain keyworks (like `cell`) might help.

**Comment by fernandes** [comment]
what if you have 2 cells for a concept like this:

1. concept/thing/show/views/show.haml (string title: ....)
2. concept/thing/index/views/index.haml (string title: ...)

how would generate the string title for both cells?

**Comment by johnlane** [comment]
I updated my [test app](https://github.com/johnlane/trailblazer-translation) so that it removes "cell" from the translation path when it is based on the class name. I did this just to see how it works and to share the idea. It cleaned up my translation file by allowing traslations to be organised around the problem domain (operations) without having to think about whether a translation is or isn't being used in a cell.

@fernandes - the path is class-deep. it doesn't include the method. So in your examples, `.title` would be the same thing in both viewss. This hasn't been an issue for me thus far (because everything's been orianised around operations) but I can see its potential for being so. I'm not sure how I would solve that except by translating `t('.show.title')` and `r('.index.title')`.

**Comment by johnlane** [comment]
The relative translation scope of a nested form (e.g. `collection do...end`) defaults to `reform.form` for the same reasons discussed above (it's an anonymous class). I don't know if there is any way to make it a named class (like there is for the contract as a whole) but a workaround is to define the scope expliciltly within the nested form (i.e. in the `collection do...end` block):
```ruby
def scope
  'thing'
end
```

**Comment by johnlane** [comment]
I have updated [my repo](https://github.com/johnlane/trailblazer-translation) to support translations on class methods. This is useful, for example, when setting properties on a contract:
```ruby
property :title, validates: {presence: { message: t('.select', name: t('.title')) } }
```

**Comment by apotonick** [comment]
@johnlane Many thanks for sharing this. Could you paste a snippet of your translation file and how/where you use those translations (using the `#t` method)? Thanks again! :heart:

**Comment by johnlane** [comment]
Sorry @apotonick I have been offline for a few days. Here's an excerpt from my translations file:
```yaml
en:

  # Generic messages
  success: 'Success!'                                                                 
  error: 'Please correct your errors and try again.'
  failure: "Sorry: it wasn't your fault, but something went wrong!"
  blank: "%{name} can't be blank"
  select: "Please select your %{name}"

  # Generic nouns
  nouns: &nouns
    name:     'name'
    forename: 'forename'
    surname:  'surname'
    password: 'password'
    password_confirmation: 'password confirmation'
    email:    'email address'
    email_confirmation: 'email address confirmation'

<<: *nouns

  # User concept
  user:
    title_prompt:    'Title'
    name_prompt: 'What is your name?'
    forename_prompt: 'Forename'
    surname_prompt:  'Surname'
    email_prompt:    'Your email address?'
    email_placeholder: 'Email'
    email_confirmation_placeholder: 'Email, again'
    password_prompt: 'Choose a password:'
    password_placeholder: 'Password'
    password_confirmation_placeholder: 'Password, again'
    password_mismatch_error: "Passwords don't match"
    password_strength_error: "Password is weak"
    success: 'Thank you, %{name}, for signing up.'
    invalid_email: 'Invalid email address'

    submit:
      create:  'Create user'
      sign_up: 'Sign up'
```

Example uses:

In operation contract (translators here are class methods):

```ruby
  class Create < Trailblazer::Operation
    include Model
    model User, :create

    class Form < Reform::Form
      property :forename,
        validates: {presence: { message: t('.blank',  name: t('.forename')) } }
      property :surname,
        validates: {presence: { message: t('.blank',  name: t('.surname'))  } }
      validates :password, unless: :authenticated?,
        presence: { message: t('.blank', name: t('.password')) }
```

In a contract validator

```ruby
def password_ok?
    unless PasswordStrength.test(password).valid?
        errors.add(:password, t('.password_strength_error'))
    end
end
```

In a cell
```ruby
def title_prompt
  @title_prompt ||= t('.title_prompt')
end
```

In a cell's view

```ruby
<%= f.input_field :password, class: "form-control",
  placeholder: t('.password_placeholder') %>
...
<%= f.submit t(".submit.#{submit_label}"), class: 'btn btn-primary' %>
```
